# Generated by Django 4.2.16 on 2025-06-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_alter_commentthread_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_group_ids",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="commentthread",
            name="user_group_ids",
            field=models.JSONField(null=True),
        ),
    ]
