# Generated by Django 5.2.12 on 2026-03-27 06:58

from typing import Any

from django.db import migrations, models


def backfill_pinned_false(apps: Any, schema_editor: Any) -> None:
    CommentThread = apps.get_model("forum", "CommentThread")
    CommentThread.objects.filter(pinned__isnull=True).update(pinned=False)


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_add_author_username_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_pinned_false, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="commentthread",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
