# Generated by Django 5.2.7 on 2025-10-30 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forum', '0004_add_author_username_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Whether this content has been identified as spam by AI moderation'),
        ),
        migrations.AddField(
            model_name='commentthread',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Whether this content has been identified as spam by AI moderation'),
        ),
        migrations.CreateModel(
            name='ModerationAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the moderation decision was made')),
                ('classifier_output', models.JSONField(help_text='Full output from the AI classifier')),
                ('reasoning', models.TextField(help_text='AI reasoning for the decision')),
                ('classification', models.CharField(choices=[('spam', 'Spam'), ('spam_or_scam', 'Spam or Scam'), ('not_spam', 'Not Spam')], help_text='AI classification result', max_length=20)),
                ('action_taken', models.CharField(choices=[('flagged', 'Content Flagged'), ('approved', 'Content Approved'), ('deleted', 'Content Deleted'), ('no_action', 'No Action Taken')], help_text='Action taken based on moderation', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score if available', null=True)),
                ('moderator_override', models.BooleanField(default=False, help_text='Whether a human moderator overrode the AI decision')),
                ('override_reason', models.TextField(blank=True, help_text='Reason for moderator override', null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(blank=True, help_text='Human moderator who made override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('original_author', models.ForeignKey(help_text='Original author of the moderated content', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Audit Log',
                'verbose_name_plural': 'Moderation Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'content_object_id'], name='forum_moder_content_44bbde_idx'), models.Index(fields=['timestamp'], name='forum_moder_timesta_0d4616_idx'), models.Index(fields=['classification'], name='forum_moder_classif_f477d2_idx'), models.Index(fields=['action_taken'], name='forum_moder_action__7d7bbb_idx'), models.Index(fields=['original_author'], name='forum_moder_origina_c51089_idx'), models.Index(fields=['moderator'], name='forum_moder_moderat_c62a1c_idx')],
            },
        ),
    ]
