# Generated by Django 5.2.10 on 2026-03-15 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_add_discussion_ban_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussionMuteRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(
                        db_index=True,
                        help_text="Course in which mute applies",
                        max_length=255,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("personal", "Personal"), ("course", "Course-wide")],
                        db_index=True,
                        default="personal",
                        help_text="Scope of the mute (personal or course-wide)",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for muting"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the mute is currently active"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("muted_at", models.DateTimeField(auto_now_add=True)),
                ("unmuted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "forum_discussion_user_mute",
            },
        ),
        migrations.AlterField(
            model_name="moderationauditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("ban_user", "Ban User"),
                    ("ban_reactivate", "Ban Reactivated"),
                    ("unban_user", "Unban User"),
                    ("ban_exception", "Ban Exception Created"),
                    ("bulk_delete", "Bulk Delete"),
                    ("flagged", "Content Flagged"),
                    ("soft_deleted", "Content Soft Deleted"),
                    ("approved", "Content Approved"),
                    ("no_action", "No Action Taken"),
                    ("flagged", "Content Flagged"),
                    ("soft_deleted", "Content Soft Deleted"),
                    ("no_action", "No Action Taken"),
                    ("mute", "Mute"),
                    ("unmute", "Unmute"),
                    ("mute_and_report", "Mute and Report"),
                ],
                db_index=True,
                default="no_action",
                help_text="Type of moderation action taken",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="moderationauditlog",
            index=models.Index(
                fields=["original_author"], name="forum_moder_origina_c51089_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationauditlog",
            index=models.Index(
                fields=["moderator"], name="forum_moder_moderat_c62a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationauditlog",
            index=models.Index(
                fields=["course_id"], name="forum_moder_course__a3357b_idx"
            ),
        ),
        migrations.AddField(
            model_name="discussionmuterecord",
            name="muted_by",
            field=models.ForeignKey(
                help_text="User performing the mute",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_muted_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussionmuterecord",
            name="muted_user",
            field=models.ForeignKey(
                help_text="User being muted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_muted_by_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussionmuterecord",
            name="unmuted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the unmute action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_mute_unactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="discussionmuterecord",
            index=models.Index(
                fields=["muted_user", "course_id", "is_active"],
                name="forum_discu_muted_u_2d9bf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discussionmuterecord",
            index=models.Index(
                fields=["muted_by", "course_id", "scope"],
                name="forum_discu_muted_b_18ad23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discussionmuterecord",
            index=models.Index(
                fields=["scope", "course_id", "is_active"],
                name="forum_discu_scope_da97a8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="discussionmuterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "personal")),
                fields=("muted_user", "muted_by", "course_id", "scope"),
                name="forum_unique_active_personal_mute",
            ),
        ),
        migrations.AddConstraint(
            model_name="discussionmuterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "course")),
                fields=("muted_user", "course_id"),
                name="forum_unique_active_course_mute",
            ),
        ),
    ]
