# Generated by Django 5.2 on 2026-08-27 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_alter_commentthread_pinned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationAuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the moderation decision was made",
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="The content body that was moderated"),
                ),
                (
                    "classifier_output",
                    models.JSONField(help_text="Full output from the AI classifier"),
                ),
                (
                    "reasoning",
                    models.TextField(help_text="AI reasoning for the decision"),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("spam", "Spam"), ("spam_or_scam", "Spam or Scam")],
                        help_text="AI classification result",
                        max_length=20,
                    ),
                ),
                (
                    "actions_taken",
                    models.JSONField(
                        default=list,
                        help_text="List of actions taken based on moderation (e.g., ['flagged', 'soft_deleted'])",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence score if available",
                        null=True,
                    ),
                ),
                (
                    "moderator_override",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a human moderator overrode the AI decision",
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(
                        blank=True, help_text="Reason for moderator override", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Audit Log",
                "verbose_name_plural": "Moderation Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="is_spam",
            field=models.BooleanField(
                default=False,
                help_text="Whether this content has been identified as spam by AI moderation",
            ),
        ),
        migrations.AddField(
            model_name="commentthread",
            name="is_spam",
            field=models.BooleanField(
                default=False,
                help_text="Whether this content has been identified as spam by AI moderation",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_spam"], name="forum_comme_is_spam_46c762_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["course_id", "is_spam"], name="forum_comme_course__4a265f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "course_id", "is_spam"],
                name="forum_comme_author__dde6dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(
                fields=["is_spam"], name="forum_comme_is_spam_0e7304_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(
                fields=["course_id", "is_spam"], name="forum_comme_course__2c84e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(
                fields=["author", "course_id", "is_spam"],
                name="forum_comme_author__96f3e5_idx",
            ),
        ),
        migrations.AddField(
            model_name="moderationauditlog",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                help_text="Human moderator who made override",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderation_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moderationauditlog",
            name="original_author",
            field=models.ForeignKey(
                help_text="Original author of the moderated content",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderated_content",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="moderationauditlog",
            index=models.Index(
                fields=["timestamp"], name="forum_moder_timesta_0d4616_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationauditlog",
            index=models.Index(
                fields=["classification"], name="forum_moder_classif_f477d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationauditlog",
            index=models.Index(
                fields=["original_author"], name="forum_moder_origina_c51089_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationauditlog",
            index=models.Index(
                fields=["moderator"], name="forum_moder_moderat_c62a1c_idx"
            ),
        ),
    ]
