# This workflow can be troubleshooted with act https://github.com/nektos/act
# For example: act --job run_tests --matrix toxenv:e2e
name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

defaults:
  run:
    shell: bash # opts into error checking

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12']
        toxenv: [py, quality, django42, django52, e2e, package]

    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Install Dependencies
        run: pip install -r requirements/ci.txt

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
